### ISSUE TITLE
compatibility request with figurant manager figu profile pics

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/eos_douane#2]
The figurant manager is intended to work in tandem with the douane app, as it allows for easy input on the SL side.
The one feature which would be wonderful to get working, is profile pictures. To get figu profile pictures working in the douane app, the following solution is suggested and requested.

- Add condition when fetching portrait
- if status like figu*, then img src should be mugs/npc/<figu_accountID>.jpg

**Comment by WafflesMcDuff** [comment]
Closed by #4
